# Copyright 2020 alex
# See LICENSE file for licensing details.
#
# This is only an example, and you should edit to suit your needs.
# If you don't need config, you can remove the file entirely.
options:
  admin_username:
    default: "admin"
    description: |
        The username for the static admin user. This must be set at deploy time,
        future changes to this config will be ignored.
    type: string
  admin_password:
    default: "admin"
    description: |
        The password for the static admin user. This must be set at deploy time,
        future changes to this config will be ignored. If left blank, the
        default password will be used.
    type: string
