# Copyright 2020 alex
# See LICENSE file for licensing details.
#
# This is only an example, and you should edit to suit your needs.
# If you don't need config, you can remove the file entirely.
options:
  nats_port:
    default: 4222
    description: The port NATS will listen on.
    type: int
